title: Pala Herbal Wellness
description: Simple, practical information about herbs, botanicals, herbal teas and everyday natural wellness.

theme: minima

baseurl: "/pala-herbal-wellness.github.io"

permalink: /:year/:month/:day/:title/

plugins:

- jekyll-feed
